import * as React from 'react'
import Head from "next/head";
import { Inter } from "next/font/google";

import { useState } from 'react';
import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });

declare global {
  namespace JSX {
    interface IntrinsicElements {
      'edje-spinner': any;
    }
  }
}

export default function Home() {
  const [active, setActive] = useState(false);

  function toggleActive() {
    const toggled = !active;
    setActive(toggled);
  }

  function getActive() {
    return JSON.stringify(active);
  }

  return (
    <>
      <Head>
        <title>EDJE Spinner Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Script src="/edje-spinner/edje-spinner.min.js" />
        <edje-spinner active={active.toString()} debug="true"></edje-spinner>
        <div style={{ position: 'relative', zIndex: 200000 }}>
          <button onClick={toggleActive}>Active</button>
        </div>
      </main>
    </>
  );
}
